enum NotificationType {
  NORMAL = "NORMAL",
  INVITATION = "INVITATION",
  ACCEPTED_INVITATION = "ACCEPTED_INVITATION",
  DECLINED_INVITATION = "DECLINED_INVITATION",
  INVITATION_CREATOR = "INVITATION_CREATOR",
  WORKSPACE_TITLE_UPDATE = "WORKSPACE_TITLE_UPDATE",
  DELETE_WORKSPACE = "DELETE_WORKSPACE",
}

export default NotificationType;
